

## Functional Analysis
# The type of input files to expect either DESeq2 (RNAseq) or deltaTE (RNAseq+RIBOseq)
diffexType: "example/deltaTE"
# Folder containing excel files for each condition of interest
diffexFolder: "example/deltaTE/"
# The column that will be used as the ID for functional analysis. It has to be compatible with the SYMBOLs in the annotation database.
idColumn: "Old_locus_tag"

# KEGG ID for the organism
keggOrgCode: "mma"
# Annotation database of the organism (including KEGG ids)
database: "example/test_database/org.Mmazei.eg.db"

# Cutoffs for ORA
padjCutoff: 0.05
log2fcCutoff: 0



